with open('input.txt', 'r') as file_object:
    pos = file_object.tell()
    print('Position =', pos)
    content = file_object.read(5)
    pos = file_object.tell()
    print('Position =', pos)
    file_object.seek(10)
    pos = file_object.tell()
    print('Position =', pos)
    content = file_object.read(2)
    print(content)
    file_object.seek(0)
    pos = file_object.tell()
    print('Position =', pos)